exclude: [
    ".git",
    "deploy.sh",
    ".gitignore",
    ".ruby-version",
    "bower.json",
    "Gemfile",
    "Gemfile.lock"
]

markdown: kramdown

author:
    name: Adam Brett
    display_name: adam
    web: http://adambrett.co.uk
    twitter: "@sixdaysad"
